sudo: false

branches:
  only:
    - master

services:
  - docker

language: node_js
node_js:
  - '6'
before_install:
  - cd app
install:
  - npm install
before_script:
  - bower install
script:
  - grunt build
  - cd ..
after_success:
  - test $TRAVIS_BRANCH = "master" \
    && docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" \
    && docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE} ${DOCKER_BUILDDIR} \
    && docker push ${DOCKER_REPO}/${DOCKER_IMAGE}
